services:

  crm_mongo:
    image: mongo:latest
    container_name: crm_mongo
    ports:
      - "27017:27017"
    volumes:
      - ./data:/data/db
    networks:
      - network
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
      MONGO_INITDB_DATABASE: crm

  crm_compass:
    image: mongo-express
    container_name: compass
    ports:
      - "28081:8081"
    networks:
      - network
    environment:
      ME_CONFIG_MONGODB_SERVER: crm_mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_URL: mongodb://root:root@crm_mongo:27017/
    depends_on:
      - crm_mongo

  crm_mailer:
      image: mailhog/mailhog
      container_name: crm_mailer
      ports:
      - "1030:1025"
      - "8030:8025"
      networks:
      - network

networks:
  network:
      driver: bridge